In [2]:
import numpy as np

In [6]:
# array
#1. create array data (1d/2d)
mylist = [1,2,3]

In [7]:
mylist

[1, 2, 3]

In [9]:
np.array(mylist)

array([1, 2, 3])

In [10]:
mymat = ([1,3,3],[1,2,3])

In [11]:
np.array(mymat) #array of arrays

array([[1, 3, 3],
       [1, 2, 3]])

In [12]:
np.arange(0,10,2) #(start,end,step)

array([0, 2, 4, 6, 8])

In [3]:
np.zeros(1)

array([ 0.])

In [4]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [5]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [7]:
np.linspace(0,5,10) ##(start,end,divisions)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [8]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
## random number
np.random.rand(10)  ##one dimension array from (0,1) uniform distribution

array([ 0.27972063,  0.92323798,  0.2097559 ,  0.08179382,  0.95742206,
        0.59845359,  0.48606856,  0.08630723,  0.02769821,  0.24233254])

In [10]:
np.random.rand(5,5)

array([[ 0.64521425,  0.88687134,  0.72169654,  0.55357704,  0.06294866],
       [ 0.3761564 ,  0.4532932 ,  0.24978401,  0.59372835,  0.36109136],
       [ 0.14423348,  0.94347167,  0.01062426,  0.62237034,  0.91853879],
       [ 0.87124473,  0.71877667,  0.42970838,  0.69282687,  0.48146393],
       [ 0.2201824 ,  0.4368548 ,  0.34156253,  0.62798279,  0.40134959]])

In [11]:
np.random.randn(2) # standard random distribution

array([ 0.34027528,  1.20110801])

In [12]:
np.random.randint(1,100,10) # random selection from a range; with replacement?

array([18, 92, 30, 15, 19, 45, 13, 33, 32, 34])

In [13]:
arr = np.arange(6)

In [14]:
arr.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
len(arr)

6

In [16]:
arr1 = arr.reshape((2,3))

In [17]:
len(arr1)

2

In [18]:
arr1.max()

5

In [27]:
## select elements from numpy array
arr = np.arange(0,10)

In [28]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
arr[(1,)]

1

In [33]:
## broadcasting

In [34]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arr[0:6] = 100

In [37]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [38]:
slice_of_arr = arr[0:6]

In [39]:
slice_of_arr[:] = 99

In [40]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [41]:
arr_copy = arr.copy()

In [42]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [43]:
arr_copy[0:10] = 100

In [44]:
arr_copy == arr

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [48]:
arr = np.arange(0,10)

In [49]:
arr = arr.reshape((2,5))

In [50]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
arr[0,1]

1

In [52]:
arr[0]

array([0, 1, 2, 3, 4])

In [53]:
arr[0][1]

1

In [54]:
arr > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True]], dtype=bool)

In [55]:
arr[arr>5]

array([6, 7, 8, 9])

In [56]:
arr_2d = np.arange(50).reshape(5,10)

In [57]:
arr_2d[arr_2d > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [61]:
##Numpy Operations 
## Array with Array
arr = np.array([1,2,3])
arr1 = np.array([2,3,4])
arr + arr1

array([3, 5, 7])

In [63]:
arr * arr1

array([ 2,  6, 12])

In [64]:
np.sqrt(arr)

array([ 1.        ,  1.41421356,  1.73205081])